-- AlterTable
ALTER TABLE "Report" ALTER COLUMN "width" SET DEFAULT 1140,
ALTER COLUMN "width" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "height" SET DEFAULT 900,
ALTER COLUMN "height" SET DATA TYPE DOUBLE PRECISION;
